
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiladores1.webappgc.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACCION_DP = 23;
  public static final int VALOR_PARAMETRO = 26;
  public static final int ACCION_MP = 24;
  public static final int PARAMETRO_OPEN = 10;
  public static final int L_LLAVE = 27;
  public static final int ETIQUETAS_CLOSE = 13;
  public static final int R_LLAVE = 28;
  public static final int ACCION_CLOSE = 5;
  public static final int GT = 19;
  public static final int ACCIONES_OPEN = 2;
  public static final int ID = 20;
  public static final int ETIQUETA_OPEN = 14;
  public static final int PARAMETROS_CLOSE = 9;
  public static final int ACCION_NP = 22;
  public static final int NOMBRE_OPEN = 17;
  public static final int PR_ID = 25;
  public static final int EOF = 0;
  public static final int FECHA = 7;
  public static final int ACCIONES_CLOSE = 3;
  public static final int XML_TAG_CLOSE = 18;
  public static final int VALOR_OPEN = 16;
  public static final int error = 1;
  public static final int ACCION_OPEN = 4;
  public static final int ETIQUETAS_OPEN = 12;
  public static final int PARAMETROS_OPEN = 8;
  public static final int SALTOLINEA = 6;
  public static final int ENTERO = 30;
  public static final int ESPACIO = 21;
  public static final int VALOR = 29;
  public static final int ETIQUETA_CLOSE = 15;
  public static final int PARAMETRO_CLOSE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ACCIONES_OPEN",
  "ACCIONES_CLOSE",
  "ACCION_OPEN",
  "ACCION_CLOSE",
  "SALTOLINEA",
  "FECHA",
  "PARAMETROS_OPEN",
  "PARAMETROS_CLOSE",
  "PARAMETRO_OPEN",
  "PARAMETRO_CLOSE",
  "ETIQUETAS_OPEN",
  "ETIQUETAS_CLOSE",
  "ETIQUETA_OPEN",
  "ETIQUETA_CLOSE",
  "VALOR_OPEN",
  "NOMBRE_OPEN",
  "XML_TAG_CLOSE",
  "GT",
  "ID",
  "ESPACIO",
  "ACCION_NP",
  "ACCION_DP",
  "ACCION_MP",
  "PR_ID",
  "VALOR_PARAMETRO",
  "L_LLAVE",
  "R_LLAVE",
  "VALOR",
  "ENTERO"
  };
}

